export const runtime = "nodejs";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import BackButton from "@/components/BackButton"; // 1. ต้อง Import เข้ามาครับ

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  
  return (
    <html lang="th" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="bg-gray-50 font-sans">
        <main className="max-w-7xl mx-auto p-2 md:p-4">
          {/* ปรับปรุงตรงนี้: ใช้ flex เพื่อให้ปุ่มกลับหน้าหลักและหัวข้ออยู่ระดับเดียวกัน */}
          <div className="flex items-center gap-2 mb-1">
             <BackButton />
             {/* หากคุณมีหัวข้อหน้าหรือชื่อหมวดหมู่ใน layout ให้ใส่ตรงนี้ 
                 หากหัวข้ออยู่ใน page.tsx ให้ข้ามไปดูวิธีแก้ที่ page.tsx ด้านล่าง */}
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}